### PR TITLE
Tutorials

### PR DESCRIPTION
**Pull request by Miking98**
Adds a tutorial walking through the various internal components of FEMR. Note that the tutorial uses a super simple toy example with synthetic data, hence `.ipynb`.

Also renamed piton -> FEMR in other tutorials

### CODE REVIEW

**Comment by Lalaland** [comment]
Nice! A couple of comments:

> target_directory = "../ignore/dataset_tutorial_target/"

Why not use an actual randomly generated temp directory here? https://docs.python.org/3/library/tempfile.html

>  fieldnames=[ 
                        "concept_id", "concept_name", "domain_id", "vocabulary_id", 
                        "concept_class_id", "standard_concept", "concept_code", 
                        "valid_start_DATE", "valid_end_DATE", "invalid_reason", 
                        "load_table_id", "load_row_id",
            ]    

Please remove load_table_id and load_row_id as those are non-standard OMOP. They need to be removed elsewhere, but that's a separate thing. 

> You can think of an EventCollection as simply an unordered list of all of our events.
> 
> An EventCollection is simply an unordered list of events, where each event is associated with a specific patient ID.

Those lines are almost duplicates. I would remove the first line.

> with contextlib.closing(event_collection.create_writer()) as writer:

Not worth fixing in this PR, but this API is quite awkward.

**Comment by ZepengHuo** [comment]
Hey guys @Lalaland @Miking98, previously `[1_run_featurizers.py](https://github.com/som-shahlab/femr/blob/main/tutorials/1_run_featurizers.py)` in `tutorials` branch can still work properly on labeling `mortality` patients, but now either that nor `main` can. I received error both on per this [file](https://docs.google.com/document/d/1mY9rO45k76_VtCM7OMjkBUFJTlL5EWAyTC5UsxuSEGA/edit?usp=sharing)

Do you mind just quickly running this one see if you have that too?

> python3 tutorials/1_run_featurizers.py \
        /local-scratch/nigam/projects/ethanid/som-rit-phi-starr-prod.starr_omop_cdm5_deid_2023_02_08_extract_v8 \
        /local-scratch/nigam/projects/zphuo/data/omop_extract/mortality \
        --labeling_function mortality \
        --max_labels_per_patient 5 \
        --num_threads 20

**Comment by Miking98** [comment]
Great points @Lalaland  -- Just made the updates!

**Comment by Miking98** [comment]
@ZepengHuo thanks for the heads up! It must have been an update with the v8 extract -- I just commented out the ontology code that it couldn't find `"Death Type/OMOP"`, and it seems to fix this error now.

@Lalaland  just want to confirm that `[ "Condition Type/OMOP4822053" ]` is the correct code set we should be using for death?

**Comment by Miking98** [comment]
Hmm, there's an unrelated error I'm now getting if I run:
```
python3 tutorials/1_run_featurizers.py \
    /local-scratch/nigam/projects/ethanid/som-rit-phi-starr-prod.starr_omop_cdm5_deid_2023_02_08_extract_v8 \
    /local-scratch/nigam/projects/zphuo/data/omop_extract/mortality \
    --labeling_function mortality \
    --max_labels_per_patient 5 \
    --num_threads 20
```

The error is:
```
RuntimeError: Prediction start time must be before prediction end time, but `prediction_start_time` is 2014-02-18 23:59:59 and `prediction_end_time` is 2014-02-18 19:45:00. Maybe you `visit_start_adjust_func()` or `visit_end_adjust_func()` in such a way that the `start` time got pushed after the `end` time?
```

It seems like a visit's start time got pushed back to 23:59:59, but the visit's end time didn't get pushed back as well?

**Comment by Miking98** [comment]
@Lalaland uncovered an inconsistency that I want to get your thoughts on --

currently, the `InpatientMortalityLabeler` is defined to make a prediction at 11:59:59pm of the day of the visit. However, this causes an error for visits that last within a single day (i.e. start = 2:00am, end = 9:00pm), because then the prediction time gets pushed back *after* the visit ends.

I think it makes sense to keep the `InpatientMortalityLabeler` time to be the actual visit start, rather than pushing it to 11:59:59pm. Otherwise, the code will crash on single day visits. Thoughts?

**Comment by rthapa84** [comment]
def get_death_concepts() -> List[str]:
    return [
        # "Death Type/OMOP generated",
        "Condition Type/OMOP4822053",
    ]

@ZepengHuo  You will need to comment out the first fine as shown above. @Miking98 Why do we have that "Death Type/OMOP generated" there?

**Comment by Lalaland** [comment]
@Miking98 

> @Lalaland just want to confirm that [ "Condition Type/OMOP4822053" ] is the correct code set we should be using for death?

I believe so, at least for STARR-OMOP. Not sure about other OMOP datasets. Ideally this would be done using hierarchy tools though.

@rthapa84 "Why do we have that "Death Type/OMOP generated" there?"

I believe that's legacy code from ehr_ml, not sure why it's still here.

> currently, the InpatientMortalityLabeler is defined to make a prediction at 11:59:59pm of the day of the visit. However, this causes an error for visits that last within a single day (i.e. start = 2:00am, end = 9:00pm), because then the prediction time gets pushed back after the visit ends.

We should not make predictions on visits that are only one day long. It's incoherent.

**Comment by Miking98** [comment]
Why is it "incoherent"?

**Comment by Lalaland** [comment]
It's incoherent because trying to predict an inpatient task after the patient has been discharged makes no sense.

**Comment by jason-fries** [comment]
Two questions/points
- For a person who has been discharged, isn't their P(Y=1) always just zero? So it's not incoherent just vacuous?
- I think there is also a mismatch between assumed temporal granularity here. You might want to predict the probability of in-hospital mortality at admission (vs end of the day of the first admission). You could imagine making hourly predictions after admission for example. In the current CLMBR formulation, which is day based, this isn't possible.

**Comment by Lalaland** [comment]
> I think there is also a mismatch between assumed temporal granularity here. You might want to predict the probability of in-hospital mortality at admission (vs end of the day of the first admission). You could imagine making hourly predictions after admission for example. In the current CLMBR formulation, which is day based, this isn't possible.

True, it might be good to have that configurable.

**Comment by Miking98** [comment]
> It's incoherent because trying to predict an inpatient task after the patient has been discharged makes no sense.

Yes but you'd only be "predict[ing] an inpatient task after the patient has been discharged" if you artificially move the visit start time to 11:59:59pm. If you don't manually adjust the visit start time, then you never run into this problem, so it sounds like it makes more sense not to adjust the start time?

**Comment by Lalaland** [comment]
> Yes but you'd only be "predict[ing] an inpatient task after the patient has been discharged" if you artificially move the visit start time to 11:59:59pm. If you don't manually adjust the visit start time, then you never run into this problem, so it sounds like it makes more sense not to adjust the start time?

Yeah, feel free to make the start time adjustment configurable. But by default, I think 99% of the time you are going to want midnight of the admission.

**Comment by Miking98** [comment]
Cool this all sounds good, thanks for the discussion.

I will put these changes into a separate branch and pull request, for now will just leave this pull request to be limited to the tutorial.

**Pull request merged**
